### ISSUE TITLE
hi, how setup this server?

### ISSUE THREAD

**Issue by lordmen99** [namtrung2212/nodejs-taxi-backend#1]
i try setup this server when done all, i connect user taxi still not loaded. stuck in front page

**Comment by lordmen99** [comment]
logcat `:W/System.err: java.net.UnknownHostException: Unable to resolve host "45.77.47.129.vultr.com": No address associated with hostname
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:440)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at java.net.InetAddress.getByName(InetAddress.java:305)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:154)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-09 22:49:00.914 8964-9294/com.sconnecting.userapp W/System.err:     at java.lang.Thread.run(Thread.java:818)`
